### ISSUE TITLE
여러 리스트 조회 시, 요청 데이터 문의 

### ISSUE THREAD

**Issue by gajeong** [hwarrk/hwarrk-back#36]
### 💬 Describe

<img width="659" alt="image" src="https://github.com/user-attachments/assets/5dc13508-1f17-4e0a-9597-622d2cce5cb2">

* 구인글 찜 get 
* 알림 get 
* 유저 찜 get 

last[..]Id  와 같은 required id 값을 필요로 하는데,, 잘못 작성하신 건지 의도한건지 모르겠어요. list 조회를 해야 id 값을 알 수 있어서요 

### 📌 Tasks

requiredID를 빼주세요

**Comment by lsh2613** [comment]
무한 스크롤 방식으로 구현한 거라 처음에는 null을 넣고 조회하면 조회된 데이터 중 lastXId 값을 반환해줍니다. 이후 조회에서는 lastXId를 넣고 조회하면 되는데 지금 null이 허용 안되어있네요 수정해서 올리겠습니다

**Comment by gajeong** [comment]
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/ad985107-2326-415f-88c9-549dd9e7fc2b">
에러 발생해요 !

**Comment by lsh2613** [comment]
이부분은 post-likes가 존재하지 않아서 발생하는 에러네요. 해당 사항은 수정하겠습니다. 데이터가 존재하면 제대로 작동할 거에요
